/**
 * 与 Rust `#[tauri::command]` 函数名一一对应的常量表。
 * 仅在 `src/commands/index.ts` 内使用——业务代码请直接 import 各命令包装函数，
 * 不要再裸写命令名字面量或在调用处引用这个表。
 */
export const TAURI_COMMAND = {
  ACQUIRE_WINDOW_KEEPALIVE: "acquire_window_keepalive",
  ADD_CLIPBOARD_APP_FROM_PATH: "add_clipboard_app_from_path",
  CHANGE_STORAGE_LOCATION: "change_storage_location",
  CHECK_FOR_UPDATES: "check_for_updates",
  CLEAN_RESOURCE_CACHE: "clean_resource_cache",
  CLEAR_CLIPBOARD_ITEMS: "clear_clipboard_items",
  CLOSE_CLIPBOARD_PREVIEW: "close_clipboard_preview",
  CREATE_CLIPBOARD_GROUP: "create_clipboard_group",
  DELETE_CLIPBOARD_GROUP: "delete_clipboard_group",
  DELETE_CLIPBOARD_ITEM: "delete_clipboard_item",
  DELETE_UNREFERENCED_CLIPBOARD_APPS: "delete_unreferenced_clipboard_apps",
  DETECT_LEGACY_DATA: "detect_legacy_data",
  DOWNLOAD_UPDATE: "download_update",
  EXPORT_HISTORY_BACKUP: "export_history_backup",
  FINISH_ONBOARDING: "finish_onboarding",
  GET_AUTOSTART: "get_autostart",
  GET_CLIPBOARD_IMAGE_PATH: "get_clipboard_image_path",
  GET_CLIPBOARD_ITEM: "get_clipboard_item",
  GET_CLIPBOARD_PREVIEW_PAYLOAD: "get_clipboard_preview_payload",
  GET_CLIPBOARD_PREVIEW_STATE: "get_clipboard_preview_state",
  GET_CONTEXT_MENU_PAYLOAD: "get_context_menu_payload",
  GET_CONTEXT_SUBMENU_PAYLOAD: "get_context_submenu_payload",
  GET_RUN_AS_ADMIN_STATUS: "get_run_as_admin_status",
  GET_SETTINGS: "get_settings",
  GET_STORAGE_LOCATION: "get_storage_location",
  GET_STORAGE_USAGE: "get_storage_usage",
  GET_UPDATE_STATUS: "get_update_status",
  GET_WINDOW_LIFECYCLE_SNAPSHOT: "get_window_lifecycle_snapshot",
  HIDE_CONTEXT_MENUS: "hide_context_menus",
  HIDE_CONTEXT_SUBMENU: "hide_context_submenu",
  HIDE_WINDOW: "hide_window",
  IMPORT_CLIPBOARD_GROUP_SVG: "import_clipboard_group_svg",
  IMPORT_HISTORY_BACKUP: "import_history_backup",
  IMPORT_LEGACY_DATA: "import_legacy_data",
  INSPECT_HISTORY_BACKUP: "inspect_history_backup",
  INSTALL_UPDATE: "install_update",
  IS_LAUNCHED_VIA_AUTOSTART: "is_launched_via_autostart",
  LIST_ALL_APPS: "list_all_apps",
  LIST_CLIPBOARD_GROUPS: "list_clipboard_groups",
  LIST_CLIPBOARD_ITEMS: "list_clipboard_items",
  NOTIFY_WINDOW_READY: "notify_window_ready",
  OPEN_CLIPBOARD_ITEM_LINK: "open_clipboard_item_link",
  OPEN_EXTERNAL_URL: "open_external_url",
  OPEN_ONBOARDING: "open_onboarding",
  OPEN_PREFERENCE_DIRECTORY: "open_preference_directory",
  OPEN_PREFERENCE_WITH_HIGHLIGHT: "open_preference_with_highlight",
  OPEN_UPDATE_WINDOW: "open_update_window",
  PASTE_CLIPBOARD_ITEM: "paste_clipboard_item",
  PLAY_COPY_SOUND: "play_copy_sound",
  POPUP_CLIPBOARD_ITEM_MENU: "popup_clipboard_item_menu",
  RELEASE_WINDOW_KEEPALIVE: "release_window_keepalive",
  RESET_SETTINGS: "reset_settings",
  RESET_STORAGE_LOCATION: "reset_storage_location",
  RESTART_AS_ADMIN: "restart_as_admin",
  RESUME_GLOBAL_SHORTCUTS: "resume_global_shortcuts",
  REVEAL_CLIPBOARD_ITEM: "reveal_clipboard_item",
  SAVE_CLIPBOARD_IMAGE_TO_FILE: "save_clipboard_image_to_file",
  SET_AUTOSTART: "set_autostart",
  SET_CLIPBOARD_WINDOW_AUTO_HIDE_SUSPENDED:
    "set_clipboard_window_auto_hide_suspended",
  SET_CLIPBOARD_WINDOW_EDITING: "set_clipboard_window_editing",
  SET_CLIPBOARD_WINDOW_PINNED: "set_clipboard_window_pinned",
  SET_ONBOARDING_STEP: "set_onboarding_step",
  SET_RUN_AS_ADMIN: "set_run_as_admin",
  SET_WINDOW_DIRTY: "set_window_dirty",
  SHOW_CLIPBOARD_PREVIEW: "show_clipboard_preview",
  SHOW_CONTEXT_SUBMENU: "show_context_submenu",
  SHOW_TASKBAR_ICON: "show_taskbar_icon",
  SHOW_WINDOW: "show_window",
  SKIP_UPDATE_VERSION: "skip_update_version",
  START_DRAG_CLIPBOARD_ITEM: "start_drag_clipboard_item",
  SUSPEND_GLOBAL_SHORTCUTS: "suspend_global_shortcuts",
  TAKE_PENDING_BACKUP: "take_pending_backup",
  TAKE_PENDING_PREFERENCE_HIGHLIGHT: "take_pending_preference_highlight",
  TOGGLE_CLIPBOARD_ITEM_FAVORITE: "toggle_clipboard_item_favorite",
  TOGGLE_CLIPBOARD_ITEM_PINNED: "toggle_clipboard_item_pinned",
  UPDATE_CLIPBOARD_GROUP: "update_clipboard_group",
  UPDATE_CLIPBOARD_GROUPS_LAYOUT: "update_clipboard_groups_layout",
  UPDATE_CLIPBOARD_ITEM_GROUP: "update_clipboard_item_group",
  UPDATE_CLIPBOARD_ITEM_NOTE: "update_clipboard_item_note",
  UPDATE_SETTINGS: "update_settings",
  WRITE_TO_CLIPBOARD: "write_to_clipboard",
} as const;

export type TauriCommand = (typeof TAURI_COMMAND)[keyof typeof TAURI_COMMAND];
