/**
 * 与 Rust `#[tauri::command]` 函数名一一对应的常量表。
 * 仅在 `src/commands/index.ts` 内使用——业务代码请直接 import 各命令包装函数，
 * 不要再裸写命令名字面量或在调用处引用这个表。
 */
export const TAURI_COMMAND = {
  ADD_CLIPBOARD_APP_FROM_PATH: "add_clipboard_app_from_path",
  CHANGE_STORAGE_LOCATION: "change_storage_location",
  CLEAN_RESOURCE_CACHE: "clean_resource_cache",
  CLEAR_CLIPBOARD_ITEMS: "clear_clipboard_items",
  CLOSE_CLIPBOARD_PREVIEW: "close_clipboard_preview",
  CREATE_CLIPBOARD_GROUP: "create_clipboard_group",
  DELETE_CLIPBOARD_GROUP: "delete_clipboard_group",
  DELETE_CLIPBOARD_ITEM: "delete_clipboard_item",
  DELETE_UNREFERENCED_CLIPBOARD_APPS: "delete_unreferenced_clipboard_apps",
  EXPORT_HISTORY_BACKUP: "export_history_backup",
  GET_AUTOSTART: "get_autostart",
  GET_CLIPBOARD_IMAGE_PATH: "get_clipboard_image_path",
  GET_CLIPBOARD_ITEM: "get_clipboard_item",
  GET_CLIPBOARD_PREVIEW_PAYLOAD: "get_clipboard_preview_payload",
  GET_CLIPBOARD_PREVIEW_STATE: "get_clipboard_preview_state",
  GET_SETTINGS: "get_settings",
  GET_STORAGE_LOCATION: "get_storage_location",
  GET_STORAGE_USAGE: "get_storage_usage",
  IMPORT_CLIPBOARD_GROUP_SVG: "import_clipboard_group_svg",
  IMPORT_HISTORY_BACKUP: "import_history_backup",
  INSPECT_HISTORY_BACKUP: "inspect_history_backup",
  IS_LAUNCHED_VIA_AUTOSTART: "is_launched_via_autostart",
  LIST_ALL_APPS: "list_all_apps",
  LIST_CLIPBOARD_GROUPS: "list_clipboard_groups",
  LIST_CLIPBOARD_ITEMS: "list_clipboard_items",
  OPEN_CLIPBOARD_ITEM_LINK: "open_clipboard_item_link",
  OPEN_EXTERNAL_URL: "open_external_url",
  OPEN_PREFERENCE_DIRECTORY: "open_preference_directory",
  PASTE_CLIPBOARD_ITEM: "paste_clipboard_item",
  PLAY_COPY_SOUND: "play_copy_sound",
  POPUP_CLIPBOARD_ITEM_MENU: "popup_clipboard_item_menu",
  RESET_SETTINGS: "reset_settings",
  RESET_STORAGE_LOCATION: "reset_storage_location",
  RESUME_GLOBAL_SHORTCUTS: "resume_global_shortcuts",
  REVEAL_CLIPBOARD_ITEM: "reveal_clipboard_item",
  SET_AUTOSTART: "set_autostart",
  SET_MAIN_WINDOW_PINNED: "set_main_window_pinned",
  SHOW_CLIPBOARD_PREVIEW: "show_clipboard_preview",
  SHOW_TASKBAR_ICON: "show_taskbar_icon",
  SHOW_WINDOW: "show_window",
  START_DRAG_CLIPBOARD_ITEM: "start_drag_clipboard_item",
  SUSPEND_GLOBAL_SHORTCUTS: "suspend_global_shortcuts",
  TOGGLE_CLIPBOARD_ITEM_FAVORITE: "toggle_clipboard_item_favorite",
  TOGGLE_CLIPBOARD_ITEM_PINNED: "toggle_clipboard_item_pinned",
  UPDATE_CLIPBOARD_GROUP: "update_clipboard_group",
  UPDATE_CLIPBOARD_ITEM_NOTE: "update_clipboard_item_note",
  UPDATE_SETTINGS: "update_settings",
  WRITE_TO_CLIPBOARD: "write_to_clipboard",
} as const;

export type TauriCommand = (typeof TAURI_COMMAND)[keyof typeof TAURI_COMMAND];
