name: 🐞 Bug Report
title: "[bug] "
description: Report a bug
labels: ["type: bug", "status: needs triage"]

body:
  - type: markdown
    attributes:
      value: |
        ## First of all
        1. Please search for [existing issues](https://github.com/EcoPasteHub/EcoPaste/issues) about this problem first.
        2. Make sure the [EcoPaste](https://github.com/EcoPasteHub/EcoPaste/releases/latest) you download is up to date.
        3. Make sure it's an issue with EcoPaste and not something else you are using.
        4. Remember to follow our community guidelines and be friendly.

  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear description of what the bug is. Include screenshots if applicable.
      placeholder: Bug description
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction
      description: A link to a reproduction repo or steps to reproduce the behaviour.
      placeholder: |
        Please provide a minimal reproduction or steps to reproduce, see this guide https://stackoverflow.com/help/minimal-reproducible-example
        Why reproduction is required? see this article https://antfu.me/posts/why-reproductions-are-required

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: A clear description of what you expected to happen.

  - type: textarea
    id: info
    attributes:
      label: Application and system information
      description: Click the Copy Info button on the About page
      render: text
      placeholder: Click the Copy Info button on the About page
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
